INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE) VALUES (1719109173, 'JUAN PEREZ');
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE) VALUES (0501320444, 'CRISTIAN PIGUAVE');

INSERT INTO PRODUCTO (ID_PRODUCTO,DESCRIPCION, PRECIO) VALUES (10,'1 CAMISETA ROJA', 100);
INSERT INTO PRODUCTO (ID_PRODUCTO,DESCRIPCION, PRECIO) VALUES (20,'1 PANTALON JEAN ', 50);
INSERT INTO PRODUCTO (ID_PRODUCTO,DESCRIPCION, PRECIO) VALUES (30,'1 CHOMPA BLANCA', 120);

INSERT INTO KARDEX (ID_KARDEX,ID_PRODUCTO, TIPO_TRANSACCION, ID_TRANSACCION, CANTIDAD, PRECIO) VALUES (1,10,'ORD', 100, 10, 100);
INSERT INTO KARDEX (ID_KARDEX,ID_PRODUCTO, TIPO_TRANSACCION, ID_TRANSACCION, CANTIDAD, PRECIO) VALUES (2,10,'VEN', 200, 5, 100);
INSERT INTO KARDEX (ID_KARDEX,ID_PRODUCTO, TIPO_TRANSACCION, ID_TRANSACCION, CANTIDAD, PRECIO) VALUES (3,30,'ORD', 300, 2, 120);
INSERT INTO KARDEX (ID_KARDEX,ID_PRODUCTO, TIPO_TRANSACCION, ID_TRANSACCION, CANTIDAD, PRECIO) VALUES (4,30,'VEN', 300, 1, 120);