CREATE TABLE CLIENTE(
	ID_CLIENTE BIGINT PRIMARY KEY,
	NOMBRE VARCHAR(200)
	);

CREATE TABLE PRODUCTO(
	ID_PRODUCTO BIGINT AUTO_INCREMENT PRIMARY KEY,
	DESCRIPCION VARCHAR(300),
	PRECIO DOUBLE
	);

CREATE TABLE VENTA(
	ID_VENTA BIGINT AUTO_INCREMENT PRIMARY KEY,
	ID_CLIENTE BIGINT,
	FECHA DATE
	);

CREATE TABLE DETALLE_VENTA(
	ID_DETALLE_VENTA BIGINT AUTO_INCREMENT PRIMARY KEY,
	ID_VENTA BIGINT,
	ID_PRODUCTO BIGINT,
	CANTIDAD BIGINT,
	PRECIO DOUBLE
	);

CREATE TABLE KARDEX(
	ID_KARDEX BIGINT,
	ID_PRODUCTO BIGINT,
	TIPO_TRANSACCION VARCHAR(3),
	ID_TRANSACCION BIGINT,
	CANTIDAD BIGINT,
	PRECIO DOUBLE
	);